services:
  monitor:
    build: .
    container_name: my-monitor-container
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - monitor_net
    # Переменные окружения здесь видны скрипту напрямую
    env_file:
      - .env

  db:
    image: postgres:15-alpine
    container_name: monitor-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - monitor_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5    

  pgadmin:
    image: dpage/pgadmin4
    container_name: monitor-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - monitor_net
    depends_on:
      db:
        condition: service_healthy 

networks:
  monitor_net:
    driver: bridge  

volumes:
  db_data:
  pgadmin_data:
